### ISSUE TITLE
Update Boom

### ISSUE THREAD

**Issue by onbjerg** [onbjerg/micro-boom#29]
Boom is 3 majors behind at the moment. The only change I've noted so far is that `Boom.wrap` is not `Boom.boomify`.

Working branch is `greenkeeper/boom-7.2.1`

**Comment by satazor** [comment]
Boom meanwhile as changed to `@boom/hapi`. It would be awesome to have this package updated to have the latest version 🙏

**Comment by onbjerg** [comment]
@satazor I'll look into it 😊

**Comment by onbjerg** [comment]
I've published v2 @satazor 🙏
